### ISSUE TITLE
Update your url blog post

### ISSUE THREAD

**Issue by h3ct0rjs** [manugarri/tweets_map#1]
Hi @manugarri, 
After checking your cool code  and your idea I want to replicate this one in my local city, I'm opening this issue just to let you know that you need to update the url in the description above the actual link is http://blog.manugarri.com/this-is-how-a-month-of-tweets-looks-in-my-town/ after searching this in your site it was returning me  a 404 http code so I tried to retrieve this using waybackmachine.org but it seems that the link or page never exist. Finally after checking your blog I could find the correct link wich is  :
http://blog.manugarri.com/plotting-100k-tweets-from-my-home-town/

Maybe this could save a lot of time to others.

Best Regards, 
Hector F. 
PD: Thanks for the notebooks. it'll be very helpful.

**Comment by manugarri** [comment]
Wow thanks! Updated :)

**Comment by h3ct0rjs** [comment]
Nice :+1:
