### ISSUE TITLE
HELP! Neutral tweets classifier

### ISSUE THREAD

**Issue by Camps94** [manugarri/tweets_map#3]
Hola Manuel, muchas gracias por tus entradas en el blog! Son muy didácticas!
No me podido postear este comentario en tu blog 
[http://pybonacci.org/2015/11/24/como-hacer-analisis-de-sentimiento-en-espanol-2/](url)
Una duda que me surge. 

1º Tu clasificador NaiveBayes lo entrenas con un input the  tweets del TASS pos/neg/neutral. Pero en el resultado final solo obtienes un '0' para los negativos y un '1' para los positivos.  ¿Hay alguna posibilidad de obtener tweets 'NEU' con tu clasificador? ¿El resultado debería ser 0.5?

2º No sería mejor hacer un primer clasificador de tweets OBJETIVO/SUBJETIVO y posteriormente a los subjetivos un clasificador POS/NEG? Si es así, ¿Conoces alguna forma de realizar este 1º clasificador? Dictionary approach? Esq los WordNet existentes están disponibles solo en inglés y no sabría como separar (NEU) / (POS+NEG)

Disculpa la extensión de mis preguntas.

Muchas gracias

Saludos

**Comment by manugarri** [comment]
Hola! Me alegro de que te sirviera.

1.) Claro, sin problemas, simplemente es un problema de clasificacion con multiples categorias. El corpus original tiene esas etiquetas, asi que deberia ser fácil de hacer.

2) Si el corpus original contiene la subjetividad, si claro. Seria mejor.

P.S. Si te lees el post completo, verás que uso una maquina de vector soporte (Linear SVC) y no un NBC.
